"""Minimal data configs for Protenix pipeline."""
import os

from my_01_study.utils.root_utils import root_path_02

SAISFOLD_ROOT = f"{root_path_02}/sais_bio/release_data/ccd_cache"
# CCD_CACHE_DIR = os.path.join(SAISFOLD_ROOT, ".cache", "ccd")
CCD_CACHE_DIR = SAISFOLD_ROOT
print("CCD_CACHE_DIR", CCD_CACHE_DIR)

CCD_COMPONENTS_FILE_PATH = os.path.join(CCD_CACHE_DIR, "components.cif")
CCD_COMPONENTS_RDKIT_MOL_FILE_PATH = os.path.join(CCD_CACHE_DIR, "components.cif.rdkit_mol.pkl")  # Generated by gen_ccd_cache.py

data_configs = {
    "ccd_components_file": CCD_COMPONENTS_FILE_PATH,
    "ccd_components_rdkit_mol_file": CCD_COMPONENTS_RDKIT_MOL_FILE_PATH,
    "num_dl_workers": 4,
    "epoch_size": 1000,
    "train_ref_pos_augment": True,
    "test_ref_pos_augment": False,
    "msa": {
        "enable": False,  # MSA disabled by default (no DBs)
        "data_dir": "",
    },
    "template": {
        "enable": False,
        "data_dir": "",
    },
}
